## Задача 1
 На складе лежат разные фрукты в разном количестве. Написать функцию, которая на вход принимает любое количество названий фруктов и их количество, а возвращает общее количество фруктов на складе
Примеры/Тесты:

    <finction_name>(apple=2, banana=12, pear=9, peach=5) -> 28

In [9]:
def num_fruits(**kwargs):
    total_fruit = sum(kwargs.values())
    return total_fruit
print(num_fruits(appple = 4, banana = 12, pear = 5,peach = 9))

30

## Задача 2
Дан список с затратами на рекламу. Но в данных есть ошибки, некоторые затраты имеют отрицательную величину. Удалите такие значения из списка и посчитайте суммарные затраты. Используйте list comprehensions.
Примеры/Тесты:

    [-12, 100, 0, 125, -90, 0, 345, 655, -1, 0, 200] -> [100, 0, 125, 0, 345, 655, 0, 200]
(*) Усложнение. Удалите отрицательные значения из списка, а нулевые значения замените на None
Примеры/Тесты:

    [-12, 100, 0, 125, -90, 0, 345, 655, -1, 0, 200] -> [100, None, 125, None, 345, 655, None, 200]

In [10]:
cost_list = [i for i in [-12, 100, 125, -90, 345, 655, -1, 0, 200] if i >= 0]

print (cost_list)
print(sum(cost_list))

[100, 125, 345, 655, 0, 200]
1425

## Задача 4 
Даны два списка: Дата покупки и Суммы покупок по датам
['2021-09-14', '2021-12-15', '2021-09-08', '2021-12-05', '2021-10-09', '2021-09-30', '2021-12-22', '2021-11-29', '2021-12-24', '2021-11-26', '2021-10-27', '2021-12-18', '2021-11-09', '2021-11-23', '2021-09-27', '2021-10-02', '2021-12-27', '2021-09-20', '2021-12-13', '2021-11-01', '2021-11-09', '2021-12-06', '2021-12-08', '2021-10-09', '2021-10-31', '2021-09-30', '2021-11-09', '2021-12-13', '2021-10-26', '2021-12-09']
[1270, 8413, 9028, 3703, 5739, 4095, 295, 4944, 5723, 3701, 4471, 651, 7037, 4274, 6275, 4988, 6930, 2971, 6592, 2004, 2822, 519, 3406, 2732, 5015, 2008, 316, 6333, 5700, 2887]
### 4.1 
Найдите, какая выручка у компании в ноябре. Используйте list comprehensions.

Ответ: 25098

In [11]:
data = ['2021-09-14', '2021-12-15', '2021-09-08', '2021-12-05', '2021-10-09', '2021-09-30', '2021-12-22', '2021-11-29', '2021-12-24', '2021-11-26', '2021-10-27', '2021-12-18', '2021-11-09', '2021-11-23', '2021-09-27', '2021-10-02', '2021-12-27', '2021-09-20', '2021-12-13', '2021-11-01', '2021-11-09', '2021-12-06', '2021-12-08', '2021-10-09', '2021-10-31', '2021-09-30', '2021-11-09', '2021-12-13', '2021-10-26', '2021-12-09']
cost = [1270, 8413, 9028, 3703, 5739, 4095, 295, 4944, 5723, 3701, 4471, 651, 7037, 4274, 6275, 4988, 6930, 2971, 6592, 2004, 2822, 519, 3406, 2732, 5015, 2008, 316, 6333, 5700, 2887]

In [81]:
# def november_cost(data1:list, date2: list)-> list:
#     new_data = []
#     for i in range(len(data1)-1):
#         if '-11-' in data1[i]:
#             new_data.append(date2[i])
#     return new_data

# print(november_cost(data, cost))
# print(sum(november_cost(data, cost)))

In [12]:
print([cost[i] for i in range(0, len(data)-1) if "-11-" in data[i]])

[4944, 3701, 7037, 4274, 2004, 2822, 316]

In [13]:
print(sum([cost[i] for i in range(0, len(data)-1) if "-11-" in data[i]]))

25098

### 4.2 
Найдите выручку компании в зависимости от месяца. Напишите функцию, которая на вход принимает списки с датами и с выручкой, а на выходе вернет словарь, где ключи - это месяцы, а значения - это выручка.
Примеры/Тесты:

<finction_name>(dates, prices) -> {'09': 25647, '12': 45452, '10': 28645, '11': 25098}
Примечание:
- Для извлечения месяца вы можете воспользоваться пакетом datetime или извлекать его как строку
- Для работы "синхронно" с двумя последовательностями вы можете использовать индекс или функцию zip. Попробуйте оба варианта.
- Используйте аннотирование типов при определении функции

In [14]:
def november(data_keys: list, cost_values: list)-> dict:
    new_dict = dict()
    for i in range(len(data_keys)):
        new_dict[data_keys[i]] = cost_values[i]
    return new_dict
november(['2021-09-14', '2021-12-15', '2021-09-08', '2021-12-05', '2021-10-09', '2021-09-30', '2021-12-22', '2021-11-29', '2021-12-24', '2021-11-26', '2021-10-27', '2021-12-18', '2021-11-09', '2021-11-23', '2021-09-27', '2021-10-02', '2021-12-27', '2021-09-20', '2021-12-13', '2021-11-01', '2021-11-09', '2021-12-06', '2021-12-08', '2021-10-09', '2021-10-31', '2021-09-30', '2021-11-09', '2021-12-13', '2021-10-26', '2021-12-09'],
[1270, 8413, 9028, 3703, 5739, 4095, 295, 4944, 5723, 3701, 4471, 651, 7037, 4274, 6275, 4988, 6930, 2971, 6592, 2004, 2822, 519, 3406, 2732, 5015, 2008, 316, 6333, 5700, 2887])

{'2021-09-14': 1270,
 '2021-12-15': 8413,
 '2021-09-08': 9028,
 '2021-12-05': 3703,
 '2021-10-09': 2732,
 '2021-09-30': 2008,
 '2021-12-22': 295,
 '2021-11-29': 4944,
 '2021-12-24': 5723,
 '2021-11-26': 3701,
 '2021-10-27': 4471,
 '2021-12-18': 651,
 '2021-11-09': 316,
 '2021-11-23': 4274,
 '2021-09-27': 6275,
 '2021-10-02': 4988,
 '2021-12-27': 6930,
 '2021-09-20': 2971,
 '2021-12-13': 6333,
 '2021-11-01': 2004,
 '2021-12-06': 519,
 '2021-12-08': 3406,
 '2021-10-31': 5015,
 '2021-10-26': 5700,
 '2021-12-09': 2887}

In [17]:
def november(data_keys: list, cost_values: list)-> dict:
    new_dict = dict()
    for i in range(len(data_keys)):
        if data[i].split('-')[1] in new_dict.keys():
            new_dict[data[i].split('-')[1]] += cost[i]
        else:
         new_dict[data[i].split('-')[1]] = cost[i]
    return new_dict
print(november(['2021-09-14', '2021-12-15', '2021-09-08', '2021-12-05', '2021-10-09', '2021-09-30', '2021-12-22', '2021-11-29', '2021-12-24', '2021-11-26', '2021-10-27', '2021-12-18', '2021-11-09', '2021-11-23', '2021-09-27', '2021-10-02', '2021-12-27', '2021-09-20', '2021-12-13', '2021-11-01', '2021-11-09', '2021-12-06', '2021-12-08', '2021-10-09', '2021-10-31', '2021-09-30', '2021-11-09', '2021-12-13', '2021-10-26', '2021-12-09'],
[1270, 8413, 9028, 3703, 5739, 4095, 295, 4944, 5723, 3701, 4471, 651, 7037, 4274, 6275, 4988, 6930, 2971, 6592, 2004, 2822, 519, 3406, 2732, 5015, 2008, 316, 6333, 5700, 2887]))

{'09': 25647, '12': 45452, '10': 28645, '11': 25098}

In [89]:
def november(data_keys: list, cost_values: list)->dict:
    dict_new = dict()
    for k,v in zip(data_keys,cost_values):
        dict_new[k]=v
    return dict_new
november(['2021-09-14', '2021-12-15', '2021-09-08', '2021-12-05', '2021-10-09', '2021-09-30', '2021-12-22', '2021-11-29', '2021-12-24', '2021-11-26', '2021-10-27', '2021-12-18', '2021-11-09', '2021-11-23', '2021-09-27', '2021-10-02', '2021-12-27', '2021-09-20', '2021-12-13', '2021-11-01', '2021-11-09', '2021-12-06', '2021-12-08', '2021-10-09', '2021-10-31', '2021-09-30', '2021-11-09', '2021-12-13', '2021-10-26', '2021-12-09'],
[1270, 8413, 9028, 3703, 5739, 4095, 295, 4944, 5723, 3701, 4471, 651, 7037, 4274, 6275, 4988, 6930, 2971, 6592, 2004, 2822, 519, 3406, 2732, 5015, 2008, 316, 6333, 5700, 2887])

{'2021-09-14': 1270,
 '2021-12-15': 8413,
 '2021-09-08': 9028,
 '2021-12-05': 3703,
 '2021-10-09': 2732,
 '2021-09-30': 2008,
 '2021-12-22': 295,
 '2021-11-29': 4944,
 '2021-12-24': 5723,
 '2021-11-26': 3701,
 '2021-10-27': 4471,
 '2021-12-18': 651,
 '2021-11-09': 316,
 '2021-11-23': 4274,
 '2021-09-27': 6275,
 '2021-10-02': 4988,
 '2021-12-27': 6930,
 '2021-09-20': 2971,
 '2021-12-13': 6333,
 '2021-11-01': 2004,
 '2021-12-06': 519,
 '2021-12-08': 3406,
 '2021-10-31': 5015,
 '2021-10-26': 5700,
 '2021-12-09': 2887}